Fix/theme options
BlueBaseJS/plugin-settings-app pull request #216
Opened 2020-12-23 07:48 UTC by zubaria1

## Description
Fixed Third option system from theme mode and title of mode.

## Screenshots (if appropriate):
<img width="621" alt="Screenshot 2020-12-23 at 12 46 52 PM" src="https://user-images.githubusercontent.com/69834893/102972548-08446400-451d-11eb-9d41-0358056a22a6.png">
Fixed:
<img width="631" alt="Screenshot 2020-12-23 at 12 47 09 PM" src="https://user-images.githubusercontent.com/69834893/102972573-12666280-451d-11eb-8a0c-66191068b903.png">

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-12-24 05:57 UTC, artalat requested changes

2020-12-24 05:57 UTC, artalat commented on src/settings/DarkModeSetting/DarkModeSetting.tsx
> +	console.log(themeMode);
remove this

2020-12-24 07:53 UTC, zubaria1 commented on src/settings/DarkModeSetting/DarkModeSetting.tsx
> +	console.log(themeMode);
removed please check

2020-12-24 08:16 UTC, artalat approved these changes

2020-12-28 07:30 UTC, merged

2021-03-11 10:06 UTC, artalat commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bluebase/plugin-settings-app/v/4.1.0)
- [GitHub release](https://github.com/BlueBaseJS/plugin-settings-app/releases/tag/v4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: